######################################################################
# Automatically generated by qmake (3.0) za feb. 24 19:22:51 2018
######################################################################

TEMPLATE = app
TARGET = factory
INCLUDEPATH += .

# Input
HEADERS += \
    herofactory.h \
    superheros.h
SOURCES += main.cpp
